//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restraurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderitems = new HashSet<Orderitem>();
        }
    
        public long OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> CustomberId { get; set; }
        public string PMethod { get; set; }
        public Nullable<decimal> GTotal { get; set; }
    
        public virtual Customber Customber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderitem> Orderitems { get; set; }
    }
}
